// IT lang variables

tinyMCE.addToLang('',{
bold_desc : 'Grassetto (Ctrl+B)',
italic_desc : 'Corsivo (Ctrl+I)',
underline_desc : 'Sottolineato (Ctrl+U)',
striketrough_desc : 'Strikethrough',
justifyleft_desc : 'Allinea a sinistra',
justifycenter_desc : 'Allinea al centro',
justifyright_desc : 'Allinea a destra',
justifyfull_desc : 'Allineamento giustificato',
bullist_desc : 'Unordered list',
numlist_desc : 'Ordered list',
outdent_desc : 'Outdent',
indent_desc : 'Indent',
undo_desc : 'Annulla (Ctrl+Z)',
redo_desc : 'Ripeti (Ctrl+Y)',
link_desc : 'Inserisci/Modifica link',
unlink_desc : 'Rimuovi link',
image_desc : 'Inserisci/Modifica immagine',
cleanup_desc : 'Rimuovi formattazione',
focus_alert : 'A editor instance must be focused before using this command.',
edit_confirm : 'Tu vuoi usare la modalità WYSIWYG per l\'area di testo?',
insert_link_title : 'Inserisci/Modifica link',
insert : 'Inserisci',
update : 'Aggiorna',
cancel : 'Annulla',
insert_link_url : 'URL Link',
insert_link_target : 'Target',
insert_link_target_same : 'Apri link nella stessa finestra',
insert_link_target_blank : 'Apri link in una nuova finestra',
insert_image_title : 'Inserisci/Modifica immagine',
insert_image_src : 'URL Immagine',
insert_image_alt : 'Descrizione immagine',
help_desc : 'Aiuto',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copia/Taglia/Incolla non sono disponibili per Mozilla Firefox.\n Si desidera ricevere ulteriori informazioni?',
popup_blocked : 'Siamo spiacenti, ma abbiamo notato che il blocco delle popup ha disabilitato una finestra che fornisce una funzionalità dell\'applicazione. Sarà necessario disattivare il blocco popup per poter utilizzare appieno questo strumento.'
});
